# Generated by Django 6.0.2 on 2026-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SHIPPING', 'Shipping'), ('DELIVERING', 'Delivering'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
